### ISSUE TITLE
worth a bug report in restlet project?

### ISSUE THREAD

**Issue by johba37** [37coins/37coins-boilerplate#8]
org.restlet.ext.jaxrs.internal.core.ResponseImpl
Feb 11, 2013 10:08:09 PM org.restlet.engine.application.StatusFilter doHandle
WARNING: Exception or error caught in status service
java.lang.AbstractMethodError: javax.ws.rs.core.Response.getStatusInfo()Ljavax/ws/rs/core/Response$StatusType;
    at javax.ws.rs.WebApplicationException.computeExceptionMessage(WebApplicationException.java:127)
    at javax.ws.rs.WebApplicationException.<init>(WebApplicationException.java:116)
    at javax.ws.rs.WebApplicationException.<init>(WebApplicationException.java:76)

when running with 
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.0-m16</version>
        </dependency>

**Comment by bradwoo8621** [comment]
Seems class org.restlet.ext.jaxrs.internal.core.ResponseImpl doesn't implement the api in javax.ws.rs-api-2.0, will it be fixed in future version?
